apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-service
  template:
    metadata:
      labels:
        app: data-service
    spec:
      containers:
      - name: data-service
        image: gcr.io/${{ secrets.GKE_PROJECT }}/data_service:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"  # Increase CPU request to 500 millicpu
          limits:
            memory: "512Mi"
            cpu: "1000m"  # Increase CPU limit to 1000 millicpu
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
