apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-service
  template:
    metadata:
      labels:
        app: data-service
    spec:
      containers:
      - name: data-service
        image: gcr.io/${{ secrets.GKE_PROJECT }}/data_service:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
